# ==========================================
#      NATURAL CORE - CONFIGURATION
# ==========================================

# Prefix untuk pesan-pesan di chat
prefix:
  admin: "&6&lNaturalCore &8» &r"
  altar: "&6&l⛩ &x&F&F&D&7&0&0&lA&x&F&F&B&E&0&0&lL&x&F&F&A&6&0&0&lT&x&F&F&8&D&0&0&lA&x&F&F&7&5&0&0&lR &8» &r"
  trader: "&8[&6Trader&8] &r"
  guide: "&8[&e&lGUIDE&8] &r"

# Pesan Umum
messages:
  no-permission: "&cMaaf, kamu tidak punya akses."
  reload-success: "&aKonfigurasi berhasil dimuat ulang!"
  reload-fail: "&cGagal memuat ulang config. Cek console!"
  cooldown: "&cTunggu &e%time% &cdetik lagi."

# Pengaturan Modul
settings:
  restart-alert-time: 10 # Detik
  broadcast-cooldown: 5 # Detik